<?php

if (!defined('ABSPATH')) die('Access denied.');

?><div id="simba-tfa-admin-wrapper" class="wrap">

	<div>
		<h1><?php echo esc_html(empty($settings_page_heading) ? 'Two Factor Authentication - Admin Settings' : $settings_page_heading); ?></h1>
		<?php
		if (!empty($admin_settings_links) && is_array($admin_settings_links)) {
			// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaping down in return value.
			echo implode(' | ', array_map(function ($val) {
				return '<a href="' . esc_url($val['url']) . '">' . esc_html($val['title']) . '</a>';
			}, $admin_settings_links));
			echo '<br>';
		}
		?>
	</div>

	<?php if (defined('TWO_FACTOR_DISABLE') && TWO_FACTOR_DISABLE) { ?>
		<div class="error">
			<h3><?php echo 'Two Factor Authentication currently disabled'; ?></h3>
			<p>
				<?php echo 'Two factor authentication is currently disabled via the TWO_FACTOR_DISABLE constant (which is mostly likely to be defined in your wp-config.php)'; ?>
			</p>
		</div>
	<?php } ?>

	<div style="max-width:800px;">

		<?php
		if (is_multisite()) {
			if (is_super_admin()) {
		?>
				<p style="font-size: 120%; font-weight: bold;">
					<?php echo 'N.B. These two-factor settings apply to your entire WordPress network. (i.e. They are not localised to one particular site).'; ?>
				</p>
		<?php
			} else {
				// Should not be possible to reach this; but an extra check does not hurt.
				die('Security check');
			}
		}
		?>

		<form method="post" action="options.php" style="margin-top: 12px">
			<?php settings_fields('tfa_user_roles_group'); ?>
			<h2><?php echo 'Make two factor authentication available'; ?></h2>
			<?php echo 'Choose which user roles will have two factor authentication available.'; ?>
			<p>
				<?php $simba_tfa->list_user_roles_checkboxes(); ?>
			</p>
			<?php submit_button(); ?>
		</form>

		<div id="simba-tfa-admin-settings-algorithm">
			<hr>
			<form method="post" action="options.php" style="margin-top: 40px">
				<?php settings_fields('simba_tfa_default_hmac_group'); ?>
				<h2><?php echo 'Default algorithm for codes generated by user devices'; ?></h2>
				<?php echo 'Your users can change this in their own settings if they want.'; ?>
				<p>
					<?php
					$totp_controller->print_default_hmac_radios();
					?></p>
				<?php submit_button(); ?>
			</form>
		</div>
	</div>
</div>